# Generated by Django 3.2.5 on 2021-07-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='startdate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='tenddesc',
            new_name='tender_description',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='tendname',
            new_name='tender_name',
        ),
    ]
