# Generated by Django 3.2.5 on 2021-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_auto_20210729_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=100)),
                ('tender_description', models.CharField(max_length=500)),
            ],
        ),
    ]
