# Generated by Django 3.2.5 on 2021-08-08 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tender', '0006_alter_bid_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenderwinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tender.tender')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tender')},
            },
        ),
    ]
