# Generated by Django 3.2.5 on 2021-08-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tender', '0009_alter_tenderwinner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderwinner',
            name='tender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tender.tender'),
        ),
        migrations.AlterField(
            model_name='tenderwinner',
            name='user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
