# Generated by Django 3.2.5 on 2021-08-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_auto_20210808_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderwinner',
            name='tender',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tender.tender'),
        ),
    ]
